Androz2091/discord-giveaways

- src/Manager.js
Now it supports custom reaction for the giveaways too.
> Support for custom reaction

- src/Giveaway.js
i use this with too many giveaways and it shows no error. I m not able to find any case which can reproduce any bug.
I like if you help me to find.
> Support exemptMembers

- src/Giveaway.js
Solve issue #77 as there is no point giveaway data for deleted giveaways.
> Delete giveaway once the message is not found

- package.json
``"start": "echo \"Error: no test specified\" && exit 1",``  should be good now
> Remove test in package.json

- README.md
- src/Giveaway.js
This was based on my comment on a issue on here: https://github.com/Androz2091/discord-giveaways/issues/140#issuecomment-748532293
> Adding MySQL example

- README.md
- package.json
- src/Giveaway.js
- src/Manager.js
Thoughts? I mostly added things that have been reported in issue.
Lmk how much I did wrong 😅🤣because this is pretty much my first real pr. _Pls don't roast me to hard 😄_
And yes, I intentionally want to merge into develop first because to 90% I have done things wrong, I didn't really test it and my base was the dev branch which is in the v.4.3.0 pr but which is not merged yet so I wouldn't know any issues of that yet.
> Merge #145

- README.md
Mongodb example leads to MySQL fixed that
> :penci: Update README.md

- README.md
- src/Constants.js
- src/Giveaway.js
- typings/index.d.ts
```js
guild.members.fetch();
```
doesn't work without the GUILD_MEMBERS intent. So all the bots without this intent are now broken... This PR supports them
> ✨ Add support for bots without GUILD_MEMBERS intent

- examples/custom-databases/mysql.js
Found the solution to fix issue #155, forgot to add JSON.parse on get data
> :bug: Fix MySQL example

- README.md
- examples/custom-databases/mongodb.js
- examples/custom-databases/mysql.js
- examples/sharding.js
- examples/simple.js
- src/Constants.js
- src/Giveaway.js
- src/Manager.js
Fixes #160
Adds solution of #175
Fixes some spelling/grammar "mistakes" and typos _beautifying_ ✨
The `giveawayEnded` event should only be emitted after a giveaway has actually ended
Thoughts?
> ⚡ Global improvements in the code and some fixes

- README.md
- examples/simple.js
- src/Giveaway.js
I added a opportunity to add the prize to a reroll message. If u want remove the readme change, since I wasn't sure about its necessity.
> ✨Add prize variable for reroll and add end method in examples

- README.md
- examples/custom-databases/enmap.js
I had tried to do the same system as quick.db when I had Enmap, but I noticed that it was not the same system (the base gets corrupted when adding). So I modified and found this solution for those who use [Enmap](https://enmap.evie.dev/).
> Add Enmap as custom database

- README.md
* Link was wrong in README.md.
> 📝 Fix Mongoose Example Link

- examples/custom-databases/mongoose.js
> ✨ Fix mongoose example error

- README.md
- examples/custom-databases/enmap.js
- examples/custom-databases/mongodb.js
- examples/custom-databases/mongoose.js
- examples/custom-databases/mysql.js
- examples/sharding.js
- examples/simple.js
- src/Constants.js
> Added embedColorEnd to the examples

- examples/custom-databases/mongoose.js
- src/Constants.js
- src/Giveaway.js
- src/Manager.js
- typings/index.d.ts
Thoughts? 
Things I updated wrong?
Things that should also get updated?
> 🏷️ Update data types

- README.md
- examples/custom-databases/mongoose.js
- package.json
- src/Constants.js
- src/Giveaway.js
- src/Manager.js
- typings/index.d.ts
`console.log(userArray)` Giveaway.js Line 398 to see the array with the bonus entries
**Format**
```js
bonusEntries: [{ bonus: (member) => member.roles.cache.get('12345' ? 1 : null), cumulative: false }]
```
Thoughts, suggestions, improvements, roasts?
If someone has a better name for the property, I'm open.
> ✨ Bonus Entries

- src/Manager.js
Fixed the error where it said options.winnerCount is not a positive integer.
> 🐛 winnerCount checking more understandable

- README.md
- examples/custom-databases/replit.js
As I experienced some problems with json storage on replit because https://github.com/AnIdiotsGuide/discordjs-bot-guide/issues/119#issuecomment-691539040
> 📦 Adding Replit database example

- src/Giveaway.js
- src/Manager.js
So this should work. #36
The limits come from https://discordjs.guide/popular-topics/embeds.html#embed-limits
Any flaws in the code?
> 🐛 Many winners embed support

- README.md
- examples/custom-databases/mongoose.js
- src/Constants.js
- src/Giveaway.js
- typings/index.d.ts
This serializes the exemptMembers function to a string, so it can be saved to the json file. I tested it and it works but maybe for some complex functions it doesn't. I will let this PR opened some days so if someone finds bugs they can report them here
> 🐛 Serialize exemptMembers function to a string

- README.md
- src/Constants.js
- src/Giveaway.js
- src/Manager.js
- typings/index.d.ts
The first change allows users to put an image with their giveaway, allowing it to be more attractive. It is an optional parameter of course, and using `.setThumbnail`.
The second change allows users to use custome emojis such as Steam logo with their prize.
VSC made auto-formats, sorry for the inconvenient.
> ✨ Add thumbnail support and use setTitle instead of setAuthor 

- .github/PULL_REQUEST_TEMPLATE.md
I allowed myself to copy the status options from discord player.
But maybe we should add some more status options?
> 🏷️ Add Pull Request Template

- README.md
- src/Constants.js
- src/Giveaway.js
This PR fixes a lot of the spelling errors in JSDoc comments and more.
ℹ️ This does not add any methods or parameters, making this a `SemVer: Patch` commit.
I'm open to any corrections and suggestions that may be suggested.
> ✨ style(*): Fix JSDoc spelling errors, and more.

- src/Manager.js
- typings/index.d.ts
This event exists but has not been typed yet.
[Source](https://github.com/Androz2091/discord-giveaways/blob/e0ee06390ce2a929df64e9bbaf5a43914d94d559/src/Manager.js#L358)
> Add typing for giveawayDeleted event

- .eslintrc.json
- package.json
- src/Giveaway.js
- src/Manager.js
- typings/index.d.ts
> refactor: import timers, event, from node:

- package.json
- typings/index.d.ts
added extraData generic type to manager so that it can give autocomplete in gw start options, edit and all.
also change declare module to top level d.ts with exports
discord.js is now a dev dependency. Also added v13.0.0 in peer deps.
more info in #413
> added extraData generic type to manager

- README.md
The README uses commas while declaring variables, to declare multiple variables at the top, but it isn't continued later on.
> Consistent variable declaration syntax.

- esm.mjs
- index.js
- package.json
The file esm.mjs is not needed, as long as you export in a manner in which ESM can infer modules' keys and values, e.g.:
```js
exports.One = 1;
exports.Two = 2;
exports.Three = 3;
```
, so I have done it as such and deleted the esm.mjs file.
> Remove unnecessary esm.mjs.

- src/Manager.js
fix regression from last commit
> fix: image support fix

- examples/custom-databases/mongoose.js
Add `image` on Mongoose example
> fix: add image on mongoose example

- README.md
- src/Constants.js
- src/Manager.js
- typings/index.d.ts
Added a new message which sets the embed title.  
Did so because many people requested to be able to set the embed title to something other than the giveaway prize
_Breaking because it would lead to un-filled-in prizes if a dev added {} inside prize_
> ✨ new title message

- README.md
- src/Manager.js
- minor JSDoc import fix
- update readme to deprecate v13 code
> Readme and JSDoc Changes
